name: deepgcn
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - cudatoolkit=9.0=h13b8566_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.3=199
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.3=py37h7e9f1db_0
  - numpy-base=1.16.3=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1b=h7b6447c_1
  - pillow=6.0.0=py37h34e0f95_0
  - pip=19.1.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.3=h0371630_0
  - pytorch=1.1.0=py3.7_cuda9.0.176_cudnn7.5.1_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - wheel=0.33.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - backcall==0.1.0
    - cycler==0.10.0
    - decorator==4.4.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.20.1
    - h5py==2.9.0
    - ipykernel==5.1.0
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - jedi==0.13.3
    - joblib==0.13.2
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.0.9
    - kiwisolver==1.1.0
    - markdown==3.1
    - matplotlib==3.1.1
    - mock==3.0.5
    - networkx==2.3
    - opencv-python==4.1.0.25
    - opt-einsum==2.3.2
    - pandas==0.24.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - plyfile==0.7
    - prompt-toolkit==2.0.9
    - protobuf==3.7.1
    - ptyprocess==0.6.0
    - pygments==2.4.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pytz==2019.1
    - pyzmq==18.0.1
    - rdflib==4.2.2
    - scikit-learn==0.21.2
    - scipy==1.3.0
    - tb-nightly==1.14.0a20190614
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - tensorflow-graphics==1.0.0
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019070801
    - tf-nightly==1.15.0.dev20190708
    - torch-cluster==1.4.2
    - torch-geometric==1.3.0
    - torch-scatter==1.3.0
    - torch-sparse==0.4.0
    - torch-spline-conv==1.1.0
    - tornado==6.0.2
    - traitlets==4.3.2
    - vtk==8.1.2
    - wcwidth==0.1.7
    - werkzeug==0.15.2
    - wrapt==1.11.2
prefix: /home/qiang/anaconda3/envs/deepgcn

